/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authCenteredRouteImport } from './routes/(auth)/_centered'
import { Route as appAuthRouteImport } from './routes/(app)/_auth'
import { Route as authCenteredRegisterRouteImport } from './routes/(auth)/_centered.register'
import { Route as authCenteredLoginRouteImport } from './routes/(auth)/_centered.login'
import { Route as appAuthProfileRouteImport } from './routes/(app)/_auth.profile'
import { Route as appAuthDashboardRouteImport } from './routes/(app)/_auth.dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authCenteredRoute = authCenteredRouteImport.update({
  id: '/(auth)/_centered',
  getParentRoute: () => rootRouteImport,
} as any)
const appAuthRoute = appAuthRouteImport.update({
  id: '/(app)/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const authCenteredRegisterRoute = authCenteredRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authCenteredRoute,
} as any)
const authCenteredLoginRoute = authCenteredLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authCenteredRoute,
} as any)
const appAuthProfileRoute = appAuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => appAuthRoute,
} as any)
const appAuthDashboardRoute = appAuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => appAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof appAuthDashboardRoute
  '/profile': typeof appAuthProfileRoute
  '/login': typeof authCenteredLoginRoute
  '/register': typeof authCenteredRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof appAuthDashboardRoute
  '/profile': typeof appAuthProfileRoute
  '/login': typeof authCenteredLoginRoute
  '/register': typeof authCenteredRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)/_auth': typeof appAuthRouteWithChildren
  '/(auth)/_centered': typeof authCenteredRouteWithChildren
  '/(app)/_auth/dashboard': typeof appAuthDashboardRoute
  '/(app)/_auth/profile': typeof appAuthProfileRoute
  '/(auth)/_centered/login': typeof authCenteredLoginRoute
  '/(auth)/_centered/register': typeof authCenteredRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/profile' | '/login' | '/register'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/profile' | '/login' | '/register'
  id:
    | '__root__'
    | '/'
    | '/(app)/_auth'
    | '/(auth)/_centered'
    | '/(app)/_auth/dashboard'
    | '/(app)/_auth/profile'
    | '/(auth)/_centered/login'
    | '/(auth)/_centered/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appAuthRoute: typeof appAuthRouteWithChildren
  authCenteredRoute: typeof authCenteredRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_centered': {
      id: '/(auth)/_centered'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authCenteredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_auth': {
      id: '/(app)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_centered/register': {
      id: '/(auth)/_centered/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authCenteredRegisterRouteImport
      parentRoute: typeof authCenteredRoute
    }
    '/(auth)/_centered/login': {
      id: '/(auth)/_centered/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authCenteredLoginRouteImport
      parentRoute: typeof authCenteredRoute
    }
    '/(app)/_auth/profile': {
      id: '/(app)/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appAuthProfileRouteImport
      parentRoute: typeof appAuthRoute
    }
    '/(app)/_auth/dashboard': {
      id: '/(app)/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appAuthDashboardRouteImport
      parentRoute: typeof appAuthRoute
    }
  }
}

interface appAuthRouteChildren {
  appAuthDashboardRoute: typeof appAuthDashboardRoute
  appAuthProfileRoute: typeof appAuthProfileRoute
}

const appAuthRouteChildren: appAuthRouteChildren = {
  appAuthDashboardRoute: appAuthDashboardRoute,
  appAuthProfileRoute: appAuthProfileRoute,
}

const appAuthRouteWithChildren =
  appAuthRoute._addFileChildren(appAuthRouteChildren)

interface authCenteredRouteChildren {
  authCenteredLoginRoute: typeof authCenteredLoginRoute
  authCenteredRegisterRoute: typeof authCenteredRegisterRoute
}

const authCenteredRouteChildren: authCenteredRouteChildren = {
  authCenteredLoginRoute: authCenteredLoginRoute,
  authCenteredRegisterRoute: authCenteredRegisterRoute,
}

const authCenteredRouteWithChildren = authCenteredRoute._addFileChildren(
  authCenteredRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appAuthRoute: appAuthRouteWithChildren,
  authCenteredRoute: authCenteredRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
